service: lambda
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  tempest-cognito-postSignup:
    handler: cognito/postSignup.handler
